apiVersion: v1
kind: ConfigMap
metadata:
    name: server-config-map
data:
    REDIS_HOST: redis
    REDIS_PORT: "6379"
    PGHOST: postgres
    PGDATABASE: postgres
    PGPORT: "5432"
    PGUSER: docker