apiVersion: v1
kind: ConfigMap
metadata:
    name: config-map
data:
    REDIS_HOST: redis-cluster-ip
    REDIS_PORT: "6379"
    PGHOST: postgres-cluster-ip
    PGPORT: "5432"
    PGDATABASE: postgres
    PGUSER: docker 
